name: Run Pint
description: Laravel code style fixer (Pint)
runs:
  using: "composite"
  steps:
    - name: Run Pint
      uses: aglipanci/laravel-pint-action@2.0.0
      with:
        configPath: "pint.json"

    - name: Commit Pint changes
      uses: stefanzweifel/git-auto-commit-action@v5
