name: ESLint

on:
  pull_request:
    branches:
      - main
      - development
      
jobs:
  eslint:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run:  |
          set -e 
          npm run fix || true 

      - name: Commit messages
        uses: stefanzweifel/git-auto-commit-action@v5
