name: PHP Actions
on:
  pull_request:
    branches:
      - main
      - development
jobs:
  php-actions:
    name: PHP actions
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, php_psr
          coverage: none

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Run Pint
        uses: ./.github/actions/pint

      - name: Run Larastan
        uses: ./.github/actions/larastan
